variables:
  DOCKER_REG: dk.jingli365.com
  DOCKER_NAME: $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME
  DOCKER_CI_NAME: $DOCKER_REG/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME:$CI_COMMIT_SHA
  DOCKER_BRANCH_NAME: $DOCKER_REG/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
  NPM_CACHE_DIR: /cache/build-cache/npmhash/
  JL_APP_DAEMON: "true"
  JL_APP_COMMAND: node main.js  >/data/log/nohup.out 2>&1
  JL_APP_NODE_ID: CI-$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  JL_APP_PORT: "8080"
stages:
  - build
  - docker
  - deploy

image: docker:git

before_script:
  - 'eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY">.k && chmod 600 .k && ssh-add .k && rm -f .k'
  - 'mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\tSendEnv JL_APP_*\n\n" > ~/.ssh/config'
  - mkdir -p /cache/build-cache/.npm && ln -s /cache/build-cache/.npm ~/

build:dist:
  stage: build
  only:
    - branches
  image: $DOCKER_REG/jl-build:v3
  tags:
    - serial
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - dist/
  script:
    - mkdir -p $NPM_CACHE_DIR/`npmhash`/node_modules && ln -s $NPM_CACHE_DIR/`npmhash`/node_modules .
    - echo `npmhash`
    - npm install
    - npm run dist

build:image:
  stage: docker
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - dist/
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker build -t $DOCKER_CI_NAME . --build-arg NPM_TOKEN=$NPM_TOKEN
    - docker push $DOCKER_CI_NAME

deploy:master:
  stage: deploy
  only:
    - /^master$/
  environment:
    name: dev
    url: https://l.jingli365.com/proj/svr-data-store
  variables:
    GIT_STRATEGY: none
    JL_APP_PLACE_API: "https://l.jingli365.com/proj/svr-place"
    JL_APP_DTASKMGR_ADDR: l.jingli365.com
    JL_APP_DTASKMGR_PORT: "14108"
    JL_APP_DTASKMGR_API: "http://l.jingli365.com/proj/svr-dtask-mgr"
    JL_APP_POSTGRES: "postgres://times:time0418@l.jingli365.com:15432/data-store"
    JL_APP_REDIS: redis://l.jingli365.com:16379
    JL_APP_ALI_WEBTRACK_URL: http://jl-data-stat.cn-beijing.log.aliyuncs.com/logstores/jl-data-stat/track
    SERVER_TYPE: develpment-server
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker pull $DOCKER_CI_NAME
    - docker tag $DOCKER_CI_NAME $DOCKER_BRANCH_NAME
    - docker push $DOCKER_BRANCH_NAME
    - echo deploy to https://l.jingli365.com
    - ssh test@l.jingli365.com /home/test/bin/docker_swarm.sh $DOCKER_REG $DOCKER_NAME $CI_COMMIT_REF_SLUG -p 8080 -p 14106:4106

deploy:test:
  stage: deploy
  only:
    - /^test$/
  environment:
    name: test
    url: https://t.jingli365.com/proj/svr-data-store
  variables:
    GIT_STRATEGY: none
    JL_APP_PLACE_API: "https://t.jingli365.com/proj/svr-place"
    JL_APP_DTASKMGR_ADDR: l.jingli365.com
    JL_APP_DTASKMGR_PORT: "14108"
    JL_APP_POSTGRES: "postgres://times:time0418@t.jingli365.com:15432/data-store"
    JL_APP_REDIS: redis://t.jingli365.com:16379
    JL_APP_ALI_WEBTRACK_URL: http://jl-data-stat.cn-beijing.log.aliyuncs.com/logstores/jl-data-stat/track
    SERVER_TYPE: test-server
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker pull $DOCKER_CI_NAME
    - docker tag $DOCKER_CI_NAME $DOCKER_BRANCH_NAME
    - docker push $DOCKER_BRANCH_NAME
    - echo deploy to https://l.jingli365.com
    - ssh test@l.jingli365.com /home/test/bin/docker_swarm.sh $DOCKER_REG $DOCKER_NAME $CI_COMMIT_REF_SLUG -p 8080 -p 14206:4106

deploy:demo:
  stage: deploy
  only:
    - /^demo$/
  environment:
    name: demo
    url: https://demo.jingli365.com/proj/svr-data-store/
  variables:
    GIT_STRATEGY: none
    JL_APP_PLACE_API: "https://demo.jingli365.com/proj/svr-place"
    JL_APP_POSTGRES: "postgres://jingli:J1n9L1.t3ch@demo.jingli365.com:5432/data-store-demo"
    JL_APP_DTASKMGR_ADDR: demo.jingli365.com
    JL_APP_DTASKMGR_PORT: "14108"
    JL_APP_REDIS: redis://demo.jingli365.com:6379
    JL_APP_ALI_WEBTRACK_URL: http://jl-data-stat.cn-beijing.log.aliyuncs.com/logstores/jl-data-stat/track
    SERVER_TYPE: release-server
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker pull $DOCKER_CI_NAME
    - docker tag $DOCKER_CI_NAME $DOCKER_BRANCH_NAME
    - docker push $DOCKER_BRANCH_NAME
    - echo deploy to https://demo.jingli365.com/proj/svr-data-store/
    - ssh test@demo.jingli365.com /home/test/bin/docker_swarm.sh $DOCKER_REG $DOCKER_NAME $CI_COMMIT_REF_SLUG -p 14206:4106

deploy:release:
  stage: deploy
  only:
    - /^release$/
  when: manual
  environment:
    name: dev
    url: https://j.jingli365.com
  variables:
    GIT_STRATEGY: none
    JL_APP_PLACE_API: "https://j.jingli365.com/proj/svr-place"
    JL_APP_DTASKMGR_ADDR: j.jingli365.com
    JL_APP_DTASKMGR_PORT: "4108"
    JL_APP_POSTGRES: "postgres://jingli:J1n9L1.t3ch@j.jingli365.com:5432/data-store"
    JL_APP_REDIS: redis://j.jingli365.com:16379
    JL_APP_ALI_WEBTRACK_URL: http://jl-data-stat.cn-beijing.log.aliyuncs.com/logstores/jl-data-stat/track
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker pull $DOCKER_CI_NAME
    - docker tag $DOCKER_CI_NAME $DOCKER_BRANCH_NAME
    - docker push $DOCKER_BRANCH_NAME
    - echo deploy to https://j.jingli365.com
    - ssh test@j.jingli365.com /home/test/bin/docker_swarm.sh $DOCKER_REG $DOCKER_NAME $CI_COMMIT_REF_SLUG -p 8080 -p 4106:4106
